### ISSUE TITLE
French Translation: sections Abstract - Introduction

### ISSUE THREAD

**Issue by jzu** [glemercier/avalanche-whitepaper#6]

**Comment by jzu** [comment]
À revoir : 

- Titre
- safety → sûreté ?
- 4e phrase de l'abstract : _Unlike traditional consensus protocols…_  incompréhensible
- Sections standard à renommer (Abstract → Résumé) sachant que french.sty fait planter la compilation
- Césures, idem, donc faciliter la césure avec des tirets optionnels
- Espaces fines insécables avant les doubles ponctuations, idem

**Comment by glemercier** [comment]
- Titre
Ca me choque pas, difficile de traduire correctement. De tout manière c'est le premier truc que la team Avalanche va voir et il y a de grandes chances qu'ils veuillent le changer

- safety → sûreté ?
j'aurais mis pareil

- 4e phrase de l'abstract : Unlike traditional consensus protocols… incompréhensible
Première partie de la phrase j'avoue que je vois pas trop mais 'bits' je le vois plutôt dans le sens "morceaux". Pour la deuxième partie je verrais un truc comme ça:

`Il ne nécessite pas que tous les participants aient une connaissance parfaite et permet donc d'atteindre des nouveaux compromis en termes de sûreté et de vivacité dans la construction de protocoles de consensus.`

- Sections standard à renommer (Abstract → Résumé) sachant que french.sty fait planter la compilation
peut-être créer une issue pour tracker ce problème

- Césures, idem, donc faciliter la césure avec des tirets optionnels
=> pas sûr de comprendre

- Espaces fines insécables avant les doubles ponctuations, idem
=> pas sûr de comprendre

**Comment by jzu** [comment]
Césures : en anglais, il est normal de voir dans un texte :
bla bla bla trans-
actions bla bla bla
Les règles des césures sont différentes en français avec coupure obligatoire entre les syllabes : 
bla bla bla tran-
sactions bla bla bla

Espaces fines insécables : avant des caractères comme : ; ! ?, en anglais, il n'y a pas d'espace mais, en français, il faut une espace insécable pour ne pas se retrouver avec un de ces caractères au début d'une ligne alors qu'il devrait suivre immédiatement. Même chose pour « ». C'est plus joli quand le blanc est moins grand avant qu'après la double ponctuation.
